name: SimpleAuth2
version: ${project.version}
main: org.ximure.simpleauth2.SimpleAuth2
api-version: 1.17
author: ximure
description: None yet
website: None
commands:
  login:
    description: Command for login on a server
    usage: /<command> пароль
  register:
    description: Command to register on a server
    usage: /<command> пароль подсказка_к_паролю
  remindpassword:
    description: Command to show your password reminder
    usage: /<command>
  cpw:
    description: Command to change your password
    usage: /<command> старый_пароль новый_пароль
  cpr:
    description: fuck this
    usage: /<command> test