name: SimpleAuth
version: ${project.version}
main: org.ximure.simpleauth.SimpleAuth
api-version: 1.16
author: ximure
website: https://github.com/ximure/simpleauth
description: Small authorization plugin which uses SQLite database
commands:
  login:
    description: Command to log in on a server
    usage: /<command> <password>
  register:
    description: Command to register on a server
    usage: /<command> <password> <password reminder>
  remindpassword:
    description: Command to remind password
    usage: /<command>
  cpw:
    aliases: [changepassword]
    description: Command to change password
    usage: /<command> <old_password> <new_password>
  cpr:
    aliases: [changepasswordreminder]
    description: Command to change password reminder
    usage: /<command> <new password reminder>