name: SimpleAuth
version: ${project.version}
main: org.ximure.simpleauth.SimpleAuth
api-version: 1.16+
author: ximure
description: Small authorization plugin using SQLite database
commands:
  login:
    description: Команда для входа на сервер
    usage: /<command> пароль
  register:
    description: Команда для регистрации на сервере
    usage: /<command> пароль подсказка_к_паролю
  remindpassword:
    description: Команда для вывода напоминания пароля
    usage: /<command>
  cpw:
    description: Команда для смены пароля
    usage: /<command> старый_пароль новый_пароль
  cpr:
    description: Команда для смены напоминания пароля
    usage: /<command> новое_напоминание